[package]
name = "shinji"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha1 = "0.10.6"
time = "0.3"
tokio = { version = "1.44.1", features = ["full"] }
warp = "0.3.7"
